Deprecation: require explicit config of proxy.https.enabled when proxy.https is modified
jupyterhub/zero-to-jupyterhub-k8s pull request #1807
Opened 2020-10-05 14:13 UTC by consideRatio

This checks for attempts to configure proxy.https without explicitly setting proxy.https.enable to true, and if so, let the template rendering fail. This is meant to help users that configured https retain the expected functionality by forcing them to use the configuration that is required to maintain such functionality.

The default value was changed in #1758.

This PR implements the idea in #1806 and thereby closes #1806.

2020-10-05 14:31 UTC, yuvipanda requested changes
I often use this - when you're deploying a hub, you want all your config set (hostnames, etc) but https turned off (while DNS is cooking). I think that's sort of the point of `enabled` flags - so you can leave everything else configured, but turn the feature off.

2020-10-05 14:42 UTC, consideRatio commented
@yuvipanda okay! So the path forward is then:
- Make it clear in the changelog that users that have configured to use proxy.https and relied on proxy.https.enable to be true now need to set it to true explicitly
- Decide if we care to provide a warning in the NOTES.txt or not. What do you think?

2020-10-05 15:22 UTC, yuvipanda commented
@consideRatio yeah, I think that's a good way to do that. Unfortunately, because HTTPS requires manual steps, we can't really have `enabled` on by default, so reverting that is gonna break something...

2020-10-06 19:53 UTC, consideRatio commented
> Decide if we care to provide a warning in the NOTES.txt or not. What do you think?

2020-10-08 12:02 UTC, consideRatio commented
Self merging this to fix some conflicts in other PRs now rather than later, this PR is a harmless deprecation warning in NOTES.txt.

2020-10-08 12:02 UTC, merged