Add revisionHistoryLimit to all deployments
jupyterhub/zero-to-jupyterhub-k8s pull request #2802
Opened 2022-07-14 07:22 UTC by mgobec

# Description

Users need to be able to control how many old ReplicaSets are retained. Some users prefer to keep minimum number or even zero to clean up clutter (ArgoCD for example) or if they use `helm rollback` instead of kubectl rollout undo to roll back.

# Changes

Added revision history limit property to all deployments and added default of 10 to values file.

2022-07-14 10:41 UTC, consideRatio requested changes
If you need this, its reasonable to support in my mind! Thanks for contributing to the jupyterhub ecosystem!

Changes requested:
- Dont let templates render this unless explicitly set by user, allow a null and integer value in schema, default to null in values. Since 0 is a falsy value, use of "with" wont work in this case but checking for the value not being nil or similar would be required.
- in the schema file, use yaml anchors like for other entries in the schema to avoid repeating the same content.
- the schema description should be limking out to k8s docs rather than describing it, see how other schema entries have linked out to k8s docs

2022-07-24 20:31 UTC, mgobec commented
@consideRatio Thanks for the code comments. I updated the PR.

2022-07-25 06:12 UTC, consideRatio requested changes
Thanks for iterating on this!

> Dont let templates render this unless explicitly set by user, allow a null and integer value in schema, default to null in values. Since 0 is a falsy value, use of "with" wont work in this case but checking for the value not being nil or similar would be required.

This is probably still not fixed, you can check if you got it fixed by using `helm template` to render the outputs and see if you render a passed `0` configuration correctly (`--set hub.revisionHistoryLimit=0`. (When doing this, you can use `--show-only` flag to avoid printing the entire helm chart and only focus on a deployment's template that you trial on.)

Please also review your PR from small formatting typos.

2022-07-25 22:31 UTC, mgobec commented
@consideRatio You are right! I completely forgot that zero isn't handled like you would normally expect. I was previously testing with values other than zero. Thank you for reviewing

2022-07-26 15:58 UTC, consideRatio reviewed
This configuration is available for StatefulSet resources and DaemonSet resources that the helm chart provides as well. I presume you have a need for this as well then, right?

2022-07-26 15:58 UTC, consideRatio commented on jupyterhub/templates/proxy/autohttps/deployment.yaml
> +  {{- end}}
```suggestion
  {{- end }}
```

2022-07-26 15:58 UTC, consideRatio commented on jupyterhub/templates/proxy/deployment.yaml
> +  {{- end}}
```suggestion
  {{- end }}
```

2022-07-26 15:58 UTC, consideRatio commented on jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
> +  {{- end}}
```suggestion
  {{- end }}
```

2022-07-26 16:22 UTC, mgobec commented
I'm not sure statefulset and deamonset support revisionhistorylimit. I have to check if the spec is the same as deployment and I'll add those.

2022-07-26 16:25 UTC, consideRatio commented
> I'm not sure statefulset and deamonset support revisionhistorylimit. I have to check if the spec is the same as deployment and I'll add those.

100%!

I checked here and found it to be the same and available for those as well, see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/

2022-07-27 14:44 UTC, consideRatio commented
@mgobec i wanted to get this PR resolved so i pushed two commits that changed the following:

1. The configuration now applies to statefulset and daemonset resources this helm chart provides as well
2. Test values are passed to verify the use of this configuration leads to valid k8s resources when rendering the helm templates
via `helm template --validate`
3. Configuration `proxy.revisionHistoryLimit` split into `proxy.chp.revisionHistoryLimit` and `proxy.traefik.revisionHistoryLimit` as those are two separate deployment resources.
4. Use of the comparison operator `eq` with `nil` and `5` led to errors using `helm` versions 3.5-3.7 while it worked well in 3.8+. Since this helm chart works well with 3.5.0 I started using the `kindIs "int"` instead which works also with helm 3.5.0+.

If this LGTY, let's go for a merge!

2022-07-27 14:44 UTC, consideRatio approved these changes

2022-08-01 04:58 UTC, mgobec commented
LGTM

2022-08-02 15:58 UTC, merged