Gateway api
jupyterhub/zero-to-jupyterhub-k8s pull request #3222
Opened 2023-09-18 10:56 UTC by Kyrremann

We are moving to Gateway API with HTTPRoute instead of using regular Ingress resources. It would be nice if this chart would allow us to make the two resources needed so we don't have to make them manually before installing the chart.

From https://gateway-api.sigs.k8s.io/

> When using the Gateway API to manage ingress traffic, the Gateway resource defines a point of access at which traffic can be routed across multiple contexts -- for example, from outside the cluster to inside the cluster (north/south traffic).

2023-09-18 11:18 UTC, Kyrremann commented
I'v forgotten to update the Values schema with documentation.

2023-09-18 13:38 UTC, Kyrremann commented on jupyterhub/values.yaml
> +    namespace: namespace-for-your-gateway
To fix the problems I had with the linting I decided to go for default values for the gateway. Hope this is okay.

2023-11-10 08:05 UTC, Kyrremann commented
Is there hope for any action here?

2023-11-10 11:20 UTC, manics commented
Is the gateway API part of the standard kubernetes distribution, or is it an add-on?

2023-11-10 11:46 UTC, Kyrremann commented
It's GA since last month: https://kubernetes.io/blog/2023/10/31/gateway-api-ga/
I know that for GKE you need enable it explicit: https://cloud.google.com/kubernetes-engine/docs/how-to/deploying-gateways#enable-gateway

2023-11-23 12:48 UTC, consideRatio requested changes
I'm a bit conservative introducing this still because I've not yet learned much about this new API, but I'm absolutely open to introducing a k8s native alternative to use of Ingress to route traffic to the jupyterhub deployment.

## Action points

To introduce this could be a notable maintenance effort long term, so I'd like to see us to quite a bit of initial maintenance up front. Here are some needs I see coming with introducing this feature.

- _Manifest tests_
  - We have tests to verify that the chart's rendered manifests are considered valid resources by a k8s api-server. This is done via lint-and-validate-values.yaml.
  - [ ] Update `lint-and-validate-values.yaml` to include testing the validity of these resources against k8s api-servers
- Networking test(s)
  - [ ] Summarized what it would take to test the networking associated with this in our CI system, to test Ingress resources we would need an ingress controller for example - we would need something similar here right?
  - [ ] Decided if we should establish a networking test
  - [ ] (conditional) Established a networking test
- _Cloud provider agnostic_
  - [ ] Ensure this PR doesn't depend on a specific cloud provider like Azure, AWS, or GCP
- [ ] _Evaluate and decide on compatibility when used with `proxy.https.enabled`_

2023-11-24 11:05 UTC, Kyrremann commented on jupyterhub/templates/httproute.yaml
> +    name: proxy-public
That's a good point, sadly this also makes the PR kinda useless for us, as we need both resources to have it running. Not sure if there is some good ways to solve this dependency on GKE.

2023-11-24 11:19 UTC, Kyrremann commented
Thanks for the reply, based on your feedback, and good observation that this is tied to GKE, maybe it's not worth spending time on this yet. If I need to create one resource outside the chart, creating another one is not that much hassle. I've already solved the problem on my side.

2023-11-24 11:58 UTC, manics commented
@Kyrremann One thing I think it'd be nice to see in Z2JH are well defined ways to extend the chart, since everyone always has their own additional requirements and as more features are added there's a combinatorial explosion of configurations which aren't tested. Do you have any ideas on changes we could make to Z2JH that would make it easier for you to add custom or other vendor specific resources without having to fork the whole chart?

2023-11-27 13:28 UTC, Kyrremann commented
Good question @manics. This time we solved it by generating the two resources from the platform that is deploying the Helm charts for us, but if it's possible we could have a variable in the Helm values that can take a random resource and just apply that 🤔 Not sure if that really works.

2024-01-17 12:45 UTC, consideRatio commented
Based on https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3222#issuecomment-1825526615 I'll go for a close on this PR for the moment, we can re-open it with ease though!

2024-01-17 12:45 UTC, closed without merging