Enable setting ipFamiles and ipFamilyPolicy
jupyterhub/zero-to-jupyterhub-k8s pull request #3485
Opened 2024-08-23 20:59 UTC by mike-matera

This pull request addresses issue #3484. It updates the service template to enable users to expose their JupyterHub on an IPv6 address if their cloud allows it.

2024-09-18 10:57 UTC, consideRatio commented
I figure we can get this PR allowing the k8s Service resource to be configurable according to k8s specification, so that other pieces can be more easily worked on towards having broader support of IPv4 / IPv6 things.

I pushed a commit providing default values and updating the schema to support configuring this, and making it possible to configure all k8s Service resources this chart provides.

2024-09-18 10:57 UTC, consideRatio approved these changes

2024-09-18 11:00 UTC, consideRatio commented on jupyterhub/templates/hub/service.yaml
> -  {{- end }}
refactor: I moved this so it was positioned as it was in the other k8s Service templates

2024-09-19 21:33 UTC, manics commented
We don't have any tests for this. What do you think about merging it after the next release? That means if we find problems with how we implement IPv6 support we can make changes to these new parameters which would otherwise count as a breaking change if they're already in a release?

2024-09-19 22:45 UTC, consideRatio commented
Thanks for the quick followup @manics, deal lets hold off until z2jh 4 is released.

2024-10-03 16:14 UTC, mike-matera commented
@manics ... Sorry I didn't see your question earlier. There are three official requirements for [IPv6 dual stack support](https://kubernetes.io/docs/concepts/services-networking/dual-stack/).

1. Kubernetes >= 1.20 
2. Support for IPv6 in your cloud provider or on your local host 
3. A network plugin that supports dual stack (Calico does)

To test IPv6 support you don't need a host with a real IPv6 address, you just need IPv6 turned on in the cluster. Clusters get an [IPv6 site local prefix](https://en.wikipedia.org/wiki/Unique_local_address) which serve the same purpose of the `10.x.x.x` addresses in the cluster.  

Thanks for working on this! At my shcool the NAT situation is super weird and the only way to make z2jh available to students on campus is to have IPv6 turned on.

2025-01-06 20:38 UTC, manics commented
Coming back to this.... assuming there are other areas that will require IPv4/IPv6 configuration what do you think about a top-level property that can be referenced in multiple places, e.g. `ipfamily` with values `ipv4`, `ipv6`, `dual`, and mark it as experimental in the schema?

2025-01-27 00:33 UTC, manics commented
I've looked into this a bit more. The ideal situation is to require no configuration, and have everything work automatically on IPv4, IPv6, and dual stack.

What happens if you set the default for `ipFamilyPolicy` to `PreferDualStack`?
https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services
> Allocates both IPv4 and IPv6 cluster IPs for the Service when dual-stack is enabled. If dual-stack is not enabled or supported, it falls back to single-stack behavior.

What happens if `ipFamilies` is set to `["IPv4","IPv6"]` on a single stack system with `PreferDualStack`- does it fail, or does it just use whatever is available?

Could you share your full Z2JH configuration? I'm trying to work through some JupyterHub IPv6 issues
- https://github.com/jupyterhub/jupyterhub/pull/4986
- https://github.com/jupyterhub/jupyterhub/pull/4988

And it would be helpful to see what you're currently using.

2025-05-29 07:16 UTC, consideRatio commented
@manics you have done a lot of work with this, do you have an idea on how to proceed?

I appreciate how this PR is very tightly scoped, allowing the Service resources of the chart to optionally be explicitly configured with `ipFamilies` and `ipFamilyPolicy`.

2025-05-30 15:40 UTC, manics commented
If possible I think we should aim for a configuration that automatically works for ipv4, ipv6, and dual stack by default, e.g. `PreferDualStack` 
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3485#issuecomment-2614662304

But keep the ability to override the parameters for edge cases.

2025-05-30 17:54 UTC, consideRatio commented on jupyterhub/values.yaml
> +    ipFamilyPolicy: ""
Nice!! Do you think this is safe or a breaking change?

2025-05-30 22:07 UTC, consideRatio requested changes
Default value for proxy service config is missing.

Once that is in, this LGTM.

Should we put the explicit preferdualstack policy for both services in a standalone PR to make it easier to discuss, review, reference, discuss, revert etc? @manics has motivated it well in this PR already, so we can have it here also.

2025-06-01 12:27 UTC, consideRatio commented
> Thanks for working on this! At my shcool the NAT situation is super weird and the only way to make z2jh available to students on campus is to have IPv6 turned on.

Thank you for sharing this @mike-matera!!! This makes me very motivated to help drive this!

@manics I'll go for a merge here, and open a PR with the change you propose on switching to PreferDualStack as its easy to isolate these changes - I have read up a bit and saw for example https://kubernetes.io/docs/concepts/services-networking/dual-stack/#switching-services-between-single-stack-and-dual-stack indicating its fine to make such changes without trouble.

2025-06-01 12:27 UTC, merged